version: "3"
services:
  app:
    image: charlottestudious/ball-sort-puzzle:latest
    restart: always
    ports:
      - "3000:3000"
    networks:
      - awesome

  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes: 
      - ./postgresdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newPassword123
      POSTGRES_DB: ball-sort-db
    networks:
      - awesome

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 4000
    ports:
      - "4000:4000"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - awesome

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/PX3U7yeKGaTvucIk1SLVfyBoXvvN35o_cYOAV61CaYE.html:/.well-known/acme-challenge/PX3U7yeKGaTvucIk1SLVfyBoXvvN35o_cYOAV61CaYE.html
    networks:
      - awesome

networks:
    awesome:
        driver: bridge 

volumes:
    postgres:
    pgadmin-data:
    nginx: