export const TOPICS_LIST = [
  {
    id: 0,
    name: 'Тема форума в одну строку',
    postsCount: 1024,
    viewsCount: 2048,
    username: 'Username',
    avatar: null,
    date: '01.01.2023',
  },
  {
    id: 1,
    name: 'Тема форума в одну строку',
    postsCount: 1024,
    viewsCount: 2048,
    username: 'Username',
    avatar: null,
    date: '01.01.2023',
  },
  {
    id: 2,
    name: 'Тема форума в одну строку',
    postsCount: 1024,
    viewsCount: 2048,
    username: 'Username',
    avatar: null,
    date: '01.01.2023',
  },
  {
    id: 3,
    name: 'Тема форума в одну строку',
    postsCount: 1024,
    viewsCount: 2048,
    username: 'Username',
    avatar: null,
    date: '01.01.2023',
  },
  {
    id: 4,
    name: 'Тема форума в одну строку',
    postsCount: 1024,
    viewsCount: 2048,
    username: 'Username',
    avatar: null,
    date: '01.01.2023',
  },
  {
    id: 5,
    name: 'Тема форума в одну строку',
    postsCount: 1024,
    viewsCount: 2048,
    username: 'Username',
    avatar: null,
    date: '01.01.2023',
  },
  {
    id: 6,
    name: 'Тема форума в одну строку',
    postsCount: 1024,
    viewsCount: 2048,
    username: 'Username',
    avatar: null,
    date: '01.01.2023',
  },
  {
    id: 7,
    name: 'Тема форума в одну строку',
    postsCount: 1024,
    viewsCount: 2048,
    username: 'Username',
    avatar: null,
    date: '01.01.2023',
  },
];
