import { GameConfig } from '../types';

const colors = {
  black: '#212329',
  red: '#c42c1e',
  green: '#0d6731',
  lightGreen: '#60d67c',
  blue: '#3b2fc0',
  lightBlue: '#54a1e5',
  orange: '#eb8b3f',
  purple: '#6d2d8e',
  yellow: '#f1d85b',
  pink: '#e3637c',
  khaki: '#769707',
  grey: '#636461',
};

export const mapColorToGradientTone = {
  [colors.red]: '#62160f',
  [colors.green]: '#06401f',
  [colors.lightGreen]: '#103e1b',
  [colors.blue]: '#161248',
  [colors.lightBlue]: '#155288',
  [colors.orange]: '#a95412',
  [colors.purple]: '#441c59',
  [colors.yellow]: '#bfa210',
  [colors.pink]: '#ad1f3b',
  [colors.khaki]: '#4a5e04',
  [colors.grey]: '#252624',
};

export const gameConfig: GameConfig = {
  maxPoints: 100000,
  grid: {
    baseGap: 6,
    flasksGap: 110,
    rowsGap: 126,
    filledFlasks: 7,
    emptyFlasks: 2,
    flasksPerRow: 5,
  },
  flask: {
    width: 62,
    height: 230,
    radius: {
      topLeft: 10,
      topRight: 10,
      bottomLeft: 25,
      bottomRight: 25,
    },
    neckSize: 15,
    lineWidth: 2,
    color: colors.grey,
    ballsGap: 1,
    maxBalls: 4,
    padding: 2,
  },
  ball: {
    radius: 26,
    borderColor: colors.grey,
    borderWidth: 1,
    velRatio: 0.05,
    vel: 15,
  },
  levels: {
    1: [
      [colors.blue, colors.blue, colors.grey, colors.pink],
      [colors.lightBlue, colors.red, colors.grey, colors.pink],
      [colors.red, colors.red, colors.lightGreen, colors.blue],
      [colors.lightGreen, colors.lightBlue, colors.lightBlue, colors.orange],
      [colors.lightGreen, colors.orange, colors.grey, colors.orange],
      [colors.orange, colors.pink, colors.grey, colors.red],
      [colors.blue, colors.lightBlue, colors.pink, colors.lightGreen],
    ],
    2: [
      [colors.blue, colors.lightBlue, colors.pink, colors.lightGreen],
      [colors.red, colors.orange, colors.grey, colors.pink],
      [colors.lightBlue, colors.blue, colors.blue, colors.orange],
      [colors.pink, colors.orange, colors.lightBlue, colors.red],
      [colors.pink, colors.blue, colors.lightGreen, colors.orange],
      [colors.grey, colors.lightGreen, colors.blue, colors.red],
      [colors.lightGreen, colors.grey, colors.red, colors.grey],
    ],
    3: [
      [colors.pink, colors.orange, colors.lightGreen, colors.red],
      [colors.orange, colors.lightBlue, colors.blue, colors.pink],
      [colors.orange, colors.grey, colors.lightGreen, colors.pink],
      [colors.pink, colors.grey, colors.red, colors.lightGreen],
      [colors.lightBlue, colors.grey, colors.grey, colors.lightBlue],
      [colors.lightGreen, colors.red, colors.blue, colors.orange],
      [colors.blue, colors.lightBlue, colors.red, colors.blue],
    ],
    4: [
      [colors.lightBlue, colors.lightGreen, colors.grey, colors.lightGreen],
      [colors.pink, colors.red, colors.orange, colors.blue],
      [colors.blue, colors.orange, colors.grey, colors.lightGreen],
      [colors.pink, colors.blue, colors.lightBlue, colors.blue],
      [colors.red, colors.red, colors.pink, colors.lightBlue],
      [colors.orange, colors.orange, colors.grey, colors.red],
      [colors.lightGreen, colors.grey, colors.pink, colors.lightBlue],
    ],
    5: [
      [colors.lightBlue, colors.red, colors.lightGreen, colors.orange],
      [colors.lightBlue, colors.lightGreen, colors.blue, colors.blue],
      [colors.grey, colors.orange, colors.red, colors.lightBlue],
      [colors.lightGreen, colors.pink, colors.pink, colors.blue],
      [colors.pink, colors.red, colors.grey, colors.orange],
      [colors.red, colors.grey, colors.lightBlue, colors.orange],
      [colors.blue, colors.lightGreen, colors.grey, colors.pink],
    ],
    6: [
      [colors.blue, colors.pink, colors.orange, colors.lightGreen],
      [colors.pink, colors.red, colors.lightGreen, colors.lightBlue],
      [colors.red, colors.lightBlue, colors.pink, colors.lightBlue],
      [colors.orange, colors.blue, colors.grey, colors.lightGreen],
      [colors.orange, colors.grey, colors.orange, colors.red],
      [colors.grey, colors.grey, colors.blue, colors.red],
      [colors.lightBlue, colors.pink, colors.lightGreen, colors.blue],
    ],
    7: [
      [colors.lightBlue, colors.lightGreen, colors.blue, colors.lightGreen],
      [colors.lightGreen, colors.blue, colors.red, colors.orange],
      [colors.pink, colors.grey, colors.grey, colors.blue],
      [colors.red, colors.pink, colors.blue, colors.grey],
      [colors.orange, colors.lightBlue, colors.pink, colors.orange],
      [colors.grey, colors.grey, colors.blue, colors.red],
      [colors.red, colors.red, colors.lightBlue, colors.grey],
    ],
    8: [
      [colors.grey, colors.pink, colors.lightGreen, colors.grey],
      [colors.pink, colors.lightBlue, colors.red, colors.blue],
      [colors.blue, colors.blue, colors.orange, colors.red],
      [colors.orange, colors.lightGreen, colors.pink, colors.orange],
      [colors.lightGreen, colors.lightGreen, colors.red, colors.orange],
      [colors.red, colors.grey, colors.lightBlue, colors.lightBlue],
      [colors.grey, colors.blue, colors.lightBlue, colors.pink],
    ],
    9: [
      [colors.red, colors.blue, colors.red, colors.lightGreen],
      [colors.lightGreen, colors.lightGreen, colors.pink, colors.lightGreen],
      [colors.lightBlue, colors.blue, colors.pink, colors.orange],
      [colors.grey, colors.lightBlue, colors.grey, colors.red],
      [colors.blue, colors.lightBlue, colors.pink, colors.red],
      [colors.lightBlue, colors.orange, colors.blue, colors.grey],
      [colors.pink, colors.orange, colors.orange, colors.grey],
    ],
    10: [
      [colors.lightGreen, colors.orange, colors.blue, colors.pink],
      [colors.grey, colors.blue, colors.red, colors.grey],
      [colors.lightBlue, colors.lightBlue, colors.grey, colors.lightGreen],
      [colors.lightBlue, colors.red, colors.blue, colors.red],
      [colors.pink, colors.grey, colors.lightBlue, colors.pink],
      [colors.blue, colors.lightGreen, colors.pink, colors.red],
      [colors.orange, colors.orange, colors.orange, colors.lightGreen],
    ],
  },
};
