
name: CD Deploy Yandex cloud

on:
  workflow_run:
    workflows: [ CI Lint ]
    branches: [ deploy ]
    types: [ completed ]

jobs:
  redeploy-project:
    name: Redeploy project
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: deploy
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: charlottestudious/ball-sort-puzzle:latest
      - name: Connect to VPS and redeploy project with new image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }}
          script: cd praktikum-game && sudo docker pull charlottestudious/ball-sort-puzzle:latest && sudo docker-compose up -d --no-deps app
