name: CD Deploy Heroku

on:
  workflow_run:
    workflows: [ CI Lint ]
    branches: [ deploy ]
    types: [ completed ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: deploy
      - name: Build and Deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:login
          heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web
          heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
